/**
 * v1 — Auto-generated from openapi.yml (REAP API v1.3.0)
 * 162 paths across 32 domains.
 * Run `npm run generate:v1` to regenerate after spec changes.
 * DO NOT edit this file manually — changes will be overwritten.
 */
const router = require('express').Router();
const makeController = require('../../lib/makeController');

// Action endpoint handler (RPC-style :verb endpoints)
function actionHandler(label) {
  return (req, res) => res.json({ success: true, action: label, params: req.params });
}

// SSE stream stub
function streamHandler(req, res) {
  res.setHeader('Content-Type', 'text/event-stream');
  res.setHeader('Cache-Control', 'no-cache');
  res.write('data: {"status":"connected"}\n\n');
  const t = setInterval(() => res.write(`data: {"tick":${Date.now()}}\n\n`), 5000);
  req.on("close", () => clearInterval(t));
}

const api_keysCtrl = makeController('v1', 'api-keys');
const auditCtrl = makeController('v1', 'audit');
const authCtrl = makeController('v1', 'auth');
const awsCtrl = makeController('v1', 'aws');
const chatCtrl = makeController('v1', 'chat');
const connector_clustersCtrl = makeController('v1', 'connector-clusters');
const connectorsCtrl = makeController('v1', 'connectors');
const credential_assignmentsCtrl = makeController('v1', 'credential-assignments');
const credential_storesCtrl = makeController('v1', 'credential-stores');
const credentialsCtrl = makeController('v1', 'credentials');
const dashboardsCtrl = makeController('v1', 'dashboards');
const delegationsCtrl = makeController('v1', 'delegations');
const devicesCtrl = makeController('v1', 'devices');
const discoveryCtrl = makeController('v1', 'discovery');
const endpointsCtrl = makeController('v1', 'endpoints');
const filesCtrl = makeController('v1', 'files');
const grafanaCtrl = makeController('v1', 'grafana');
const idpCtrl = makeController('v1', 'idp');
const integrationsCtrl = makeController('v1', 'integrations');
const invitationsCtrl = makeController('v1', 'invitations');
const knowledgeCtrl = makeController('v1', 'knowledge');
const membershipsCtrl = makeController('v1', 'memberships');
const metricsCtrl = makeController('v1', 'metrics');
const mspCtrl = makeController('v1', 'msp');
const orgsCtrl = makeController('v1', 'orgs');
const rolesCtrl = makeController('v1', 'roles');
const runbooksCtrl = makeController('v1', 'runbooks');
const secretsCtrl = makeController('v1', 'secrets');
const signalsCtrl = makeController('v1', 'signals');
const sitesCtrl = makeController('v1', 'sites');
const topologyCtrl = makeController('v1', 'topology');
const visibilityCtrl = makeController('v1', 'visibility');

// ── api-keys ────────────────────────────────────────────────────
router.get('/orgs/:orgId/api-keys', api_keysCtrl.getOne);
router.post('/orgs/:orgId/api-keys', api_keysCtrl.create);
router.get('/orgs/:orgId/api-keys/:apiKeyId', api_keysCtrl.getOne);
router.patch('/orgs/:orgId/api-keys/:apiKeyId', api_keysCtrl.update);
router.delete('/orgs/:orgId/api-keys/:apiKeyId', api_keysCtrl.remove);

// ── audit ───────────────────────────────────────────────────────
router.get('/orgs/:orgId/audit/events', auditCtrl.getOne);
router.get('/orgs/:orgId/audit/events/:eventId', auditCtrl.getOne);

// ── auth ────────────────────────────────────────────────────────
router.post('/auth/discover/start', authCtrl.create);
router.post('/auth/discover/verify', authCtrl.create);
router.post('/auth/password/register', authCtrl.create);
router.post('/auth/password/verify', authCtrl.create);
router.post('/auth/password/reset', authCtrl.create);
router.post('/auth/password/change', authCtrl.create);
router.post('/auth/passkeys/attest', authCtrl.create);
router.post('/auth/passkeys/attest/verify', authCtrl.create);
router.post('/auth/passkeys/assert', authCtrl.create);
router.post('/auth/passkeys/assert/verify', authCtrl.create);
router.post('/auth/token', authCtrl.create);
router.post('/auth/logout', authCtrl.create);
router.get('/auth/me', authCtrl.getAll);
router.post('/auth/invitations/accept', authCtrl.create);
router.get('/orgs/:orgId/auth/policy', authCtrl.getOne);
router.put('/orgs/:orgId/auth/policy', authCtrl.update);

// ── aws ─────────────────────────────────────────────────────────
router.post('/orgs/:orgId/aws/cloudtrail', awsCtrl.create);
router.post('/orgs/:orgId/aws/flowlogs', awsCtrl.create);
router.post('/orgs/:orgId/aws/cloudwatch-logs', awsCtrl.create);

// ── chat ────────────────────────────────────────────────────────
router.get('/orgs/:orgId/chat/threads', chatCtrl.getOne);
router.post('/orgs/:orgId/chat/threads', chatCtrl.create);
router.post('/orgs/:orgId/chat/threads/:threadId/interact', chatCtrl.create);
router.post('/orgs/:orgId/chat/rag-lookup', chatCtrl.create);
router.get('/orgs/:orgId/chat/rag-collections/:collection/documents', chatCtrl.getOne);
router.get('/orgs/:orgId/chat/threads/:threadId', chatCtrl.getOne);
router.patch('/orgs/:orgId/chat/threads/:threadId', chatCtrl.update);
router.delete('/orgs/:orgId/chat/threads/:threadId', chatCtrl.remove);
router.get('/orgs/:orgId/chat/threads/:threadId/messages', chatCtrl.getOne);
router.get('/orgs/:orgId/chat/messages/:messageId', chatCtrl.getOne);
router.get('/orgs/:orgId/chat/runs', chatCtrl.getOne);
router.get('/orgs/:orgId/chat/runs/:runId', chatCtrl.getOne);
router.post('/orgs/:orgId/chat/runs/:runId', chatCtrl.create);
router.get('/orgs/:orgId/chat/runs/:runId/events', chatCtrl.getOne);
router.get('/orgs/:orgId/chat/runs/:runId/artifacts', chatCtrl.getOne);
router.get('/orgs/:orgId/chat/runs/:runId/artifacts/:artifactId', chatCtrl.getOne);
router.get('/orgs/:orgId/chat/artifacts/:artifactId', chatCtrl.getOne);
router.get('/orgs/:orgId/chat/artifacts/:artifactId/stream', streamHandler);
router.post('/orgs/:orgId/chat/runs/:runId/ratings', chatCtrl.create);
router.post('/orgs/:orgId/chat/messages/:messageId/reactions', chatCtrl.create);

// ── connector-clusters ──────────────────────────────────────────
router.get('/orgs/:orgId/connector-clusters', connector_clustersCtrl.getOne);
router.post('/orgs/:orgId/connector-clusters', connector_clustersCtrl.create);
router.get('/orgs/:orgId/connector-clusters/:clusterId', connector_clustersCtrl.getOne);
router.patch('/orgs/:orgId/connector-clusters/:clusterId', connector_clustersCtrl.update);
router.delete('/orgs/:orgId/connector-clusters/:clusterId', connector_clustersCtrl.remove);
router.post('/orgs/:orgId/connector-clusters/:clusterId/sites:attach', actionHandler('attach'));
router.post('/orgs/:orgId/connector-clusters/:clusterId/sites:detach', actionHandler('detach'));

// ── connectors ──────────────────────────────────────────────────
router.get('/orgs/:orgId/connectors', connectorsCtrl.getOne);
router.post('/orgs/:orgId/connectors', connectorsCtrl.create);
router.get('/orgs/:orgId/connectors/:connectorId', connectorsCtrl.getOne);
router.patch('/orgs/:orgId/connectors/:connectorId', connectorsCtrl.update);
router.delete('/orgs/:orgId/connectors/:connectorId', connectorsCtrl.remove);
router.get('/orgs/:orgId/connectors/:connectorId/userdata', connectorsCtrl.getOne);

// ── credential-assignments ──────────────────────────────────────
router.get('/orgs/:orgId/credential-assignments', credential_assignmentsCtrl.getOne);
router.post('/orgs/:orgId/credential-assignments', credential_assignmentsCtrl.create);
router.get('/orgs/:orgId/credential-assignments/:assignmentId', credential_assignmentsCtrl.getOne);
router.patch('/orgs/:orgId/credential-assignments/:assignmentId', credential_assignmentsCtrl.update);
router.delete('/orgs/:orgId/credential-assignments/:assignmentId', credential_assignmentsCtrl.remove);

// ── credential-stores ───────────────────────────────────────────
router.get('/orgs/:orgId/credential-stores', credential_storesCtrl.getOne);
router.post('/orgs/:orgId/credential-stores', credential_storesCtrl.create);
router.get('/orgs/:orgId/credential-stores/:storeId', credential_storesCtrl.getOne);
router.patch('/orgs/:orgId/credential-stores/:storeId', credential_storesCtrl.update);
router.delete('/orgs/:orgId/credential-stores/:storeId', credential_storesCtrl.remove);

// ── credentials ─────────────────────────────────────────────────
router.get('/orgs/:orgId/credentials', credentialsCtrl.getOne);
router.post('/orgs/:orgId/credentials', credentialsCtrl.create);
router.get('/orgs/:orgId/credentials/:credentialId', credentialsCtrl.getOne);
router.patch('/orgs/:orgId/credentials/:credentialId', credentialsCtrl.update);
router.delete('/orgs/:orgId/credentials/:credentialId', credentialsCtrl.remove);

// ── dashboards ──────────────────────────────────────────────────
router.get('/orgs/:orgId/dashboards/templates', dashboardsCtrl.getOne);
router.get('/orgs/:orgId/dashboards/telemetry-targets', dashboardsCtrl.getOne);
router.get('/orgs/:orgId/dashboards/recommended', dashboardsCtrl.getOne);
router.get('/orgs/:orgId/dashboards/recommended-grafana', dashboardsCtrl.getOne);

// ── delegations ─────────────────────────────────────────────────
router.get('/orgs/:orgId/delegations', delegationsCtrl.getOne);
router.get('/orgs/:orgId/delegations/:delegationId', delegationsCtrl.getOne);
router.patch('/orgs/:orgId/delegations/:delegationId', delegationsCtrl.update);
router.get('/orgs/:orgId/delegations/invites', delegationsCtrl.getOne);
router.post('/orgs/:orgId/delegations/invites', delegationsCtrl.create);
router.post('/orgs/:orgId/delegations/invites/:inviteId:resend', actionHandler('resend'));
router.delete('/orgs/:orgId/delegations/invites/:inviteId', delegationsCtrl.remove);

// ── devices ─────────────────────────────────────────────────────
router.get('/orgs/:orgId/devices', devicesCtrl.getOne);
router.post('/orgs/:orgId/devices', devicesCtrl.create);
router.get('/orgs/:orgId/devices/:deviceId', devicesCtrl.getOne);
router.patch('/orgs/:orgId/devices/:deviceId', devicesCtrl.update);
router.delete('/orgs/:orgId/devices/:deviceId', devicesCtrl.remove);
router.get('/orgs/:orgId/devices/:deviceId/running-config', devicesCtrl.getOne);
router.get('/orgs/:orgId/devices/:deviceId/running-config/versions', devicesCtrl.getOne);
router.get('/orgs/:orgId/devices/:deviceId/running-config/diff', devicesCtrl.getOne);
router.get('/orgs/:orgId/devices/:deviceId/running-config/startup-diff', devicesCtrl.getOne);
router.get('/orgs/:orgId/devices/merge', devicesCtrl.getOne);
router.post('/orgs/:orgId/devices/merge', devicesCtrl.create);
router.get('/orgs/:orgId/devices/:deviceId/topology', devicesCtrl.getOne);

// ── discovery ───────────────────────────────────────────────────
router.get('/orgs/:orgId/discovery/jobs', discoveryCtrl.getOne);
router.post('/orgs/:orgId/discovery/jobs', discoveryCtrl.create);
router.get('/orgs/:orgId/discovery/jobs/:jobId', discoveryCtrl.getOne);
router.patch('/orgs/:orgId/discovery/jobs/:jobId', discoveryCtrl.update);
router.delete('/orgs/:orgId/discovery/jobs/:jobId', discoveryCtrl.remove);
router.get('/orgs/:orgId/discovery/jobs/:jobId/runs', discoveryCtrl.getOne);
router.post('/orgs/:orgId/discovery/jobs/:jobId/runs', discoveryCtrl.create);
router.get('/orgs/:orgId/discovery/jobs/:jobId/runs/:runId', discoveryCtrl.getOne);
router.post('/orgs/:orgId/discovery/jobs/:jobId/runs/:runId', discoveryCtrl.create);
router.get('/orgs/:orgId/discovery/jobs/:jobId/runs/:runId/events', discoveryCtrl.getOne);
router.get('/orgs/:orgId/discovery/sites/:siteId/schedule-capabilities', discoveryCtrl.getOne);

// ── endpoints ───────────────────────────────────────────────────
router.get('/orgs/:orgId/endpoints', endpointsCtrl.getOne);
router.get('/orgs/:orgId/endpoints/:endpointId', endpointsCtrl.getOne);
router.delete('/orgs/:orgId/endpoints/:endpointId', endpointsCtrl.remove);

// ── files ───────────────────────────────────────────────────────
router.post('/orgs/:orgId/files', filesCtrl.create);
router.get('/orgs/:orgId/files/:fileId', filesCtrl.getOne);

// ── grafana ─────────────────────────────────────────────────────
router.post('/orgs/:orgId/grafana/embed-session', grafanaCtrl.create);

// ── idp ─────────────────────────────────────────────────────────
router.get('/orgs/:orgId/idp/connections', idpCtrl.getOne);
router.post('/orgs/:orgId/idp/connections', idpCtrl.create);
router.get('/orgs/:orgId/idp/connections/:connectionId', idpCtrl.getOne);
router.patch('/orgs/:orgId/idp/connections/:connectionId', idpCtrl.update);
router.delete('/orgs/:orgId/idp/connections/:connectionId', idpCtrl.remove);
router.get('/orgs/:orgId/idp/connections/:connectionId/mappings', idpCtrl.getOne);
router.post('/orgs/:orgId/idp/connections/:connectionId/mappings', idpCtrl.create);
router.get('/orgs/:orgId/idp/connections/:connectionId/mappings/:ruleId', idpCtrl.getOne);
router.patch('/orgs/:orgId/idp/connections/:connectionId/mappings/:ruleId', idpCtrl.update);
router.delete('/orgs/:orgId/idp/connections/:connectionId/mappings/:ruleId', idpCtrl.remove);

// ── integrations ────────────────────────────────────────────────
router.get('/orgs/:orgId/integrations/aws/cloud-access', integrationsCtrl.getOne);
router.post('/orgs/:orgId/integrations/aws/cloud-access/quick-create', integrationsCtrl.create);
router.get('/orgs/:orgId/integrations/aws/cloudtrail', integrationsCtrl.getOne);
router.post('/orgs/:orgId/integrations/aws/cloudtrail', integrationsCtrl.create);
router.get('/orgs/:orgId/integrations/aws/cloudtrail/:connectionId', integrationsCtrl.getOne);
router.delete('/orgs/:orgId/integrations/aws/cloudtrail/:connectionId', integrationsCtrl.remove);
router.post('/orgs/:orgId/integrations/aws/cloudtrail/:connectionId/enable', integrationsCtrl.create);
router.post('/orgs/:orgId/integrations/aws/cloudtrail/:connectionId/disable', integrationsCtrl.create);
router.get('/orgs/:orgId/integrations/aws/flowlogs', integrationsCtrl.getOne);
router.post('/orgs/:orgId/integrations/aws/flowlogs', integrationsCtrl.create);
router.get('/orgs/:orgId/integrations/aws/flowlogs/resources', integrationsCtrl.getOne);
router.get('/orgs/:orgId/integrations/aws/flowlogs/:connectionId', integrationsCtrl.getOne);
router.delete('/orgs/:orgId/integrations/aws/flowlogs/:connectionId', integrationsCtrl.remove);
router.post('/orgs/:orgId/integrations/aws/flowlogs/:connectionId/enable', integrationsCtrl.create);
router.post('/orgs/:orgId/integrations/aws/flowlogs/:connectionId/disable', integrationsCtrl.create);
router.get('/orgs/:orgId/integrations/aws/cloudwatch-logs', integrationsCtrl.getOne);
router.post('/orgs/:orgId/integrations/aws/cloudwatch-logs', integrationsCtrl.create);
router.get('/orgs/:orgId/integrations/aws/cloudwatch-logs/:connectionId', integrationsCtrl.getOne);
router.delete('/orgs/:orgId/integrations/aws/cloudwatch-logs/:connectionId', integrationsCtrl.remove);
router.post('/orgs/:orgId/integrations/aws/cloudwatch-logs/:connectionId/enable', integrationsCtrl.create);
router.post('/orgs/:orgId/integrations/aws/cloudwatch-logs/:connectionId/disable', integrationsCtrl.create);

// ── invitations ─────────────────────────────────────────────────
router.get('/orgs/:orgId/invitations', invitationsCtrl.getOne);
router.post('/orgs/:orgId/invitations', invitationsCtrl.create);
router.get('/orgs/:orgId/invitations/:invitationId', invitationsCtrl.getOne);
router.delete('/orgs/:orgId/invitations/:invitationId', invitationsCtrl.remove);
router.post('/orgs/:orgId/invitations/:invitationId/send', invitationsCtrl.create);

// ── knowledge ───────────────────────────────────────────────────
router.get('/orgs/:orgId/knowledge/documents', knowledgeCtrl.getOne);
router.post('/orgs/:orgId/knowledge/documents', knowledgeCtrl.create);
router.get('/orgs/:orgId/knowledge/document-types/weaviate-classes', knowledgeCtrl.getOne);
router.get('/orgs/:orgId/knowledge/chunk-preview/jobs', knowledgeCtrl.getOne);
router.post('/orgs/:orgId/knowledge/chunk-preview/jobs', knowledgeCtrl.create);
router.get('/orgs/:orgId/knowledge/chunk-preview/jobs/:jobId', knowledgeCtrl.getOne);
router.get('/orgs/:orgId/knowledge/chunk-preview/jobs/:jobId/result', knowledgeCtrl.getOne);
router.get('/orgs/:orgId/knowledge/chunk-preview/jobs/:jobId/source', knowledgeCtrl.getOne);
router.post('/orgs/:orgId/knowledge/chunk-preview/jobs/:jobId:cancel', actionHandler('cancel'));

// ── memberships ─────────────────────────────────────────────────
router.get('/orgs/:orgId/memberships', membershipsCtrl.getOne);
router.post('/orgs/:orgId/memberships', membershipsCtrl.create);
router.get('/orgs/:orgId/memberships/:membershipId', membershipsCtrl.getOne);
router.patch('/orgs/:orgId/memberships/:membershipId', membershipsCtrl.update);
router.delete('/orgs/:orgId/memberships/:membershipId', membershipsCtrl.remove);

// ── metrics ─────────────────────────────────────────────────────
router.post('/orgs/:orgId/metrics/query', metricsCtrl.create);
router.post('/orgs/:orgId/metrics/query_range', metricsCtrl.create);

// ── msp ─────────────────────────────────────────────────────────
router.post('/msp/delegations/accept', mspCtrl.create);
router.get('/msp/delegations', mspCtrl.getAll);
router.get('/msp/delegations/:delegationId', mspCtrl.getOne);

// ── orgs ────────────────────────────────────────────────────────
router.get('/orgs', orgsCtrl.getAll);
router.post('/orgs', orgsCtrl.create);
router.get('/orgs/:orgId', orgsCtrl.getOne);
router.patch('/orgs/:orgId', orgsCtrl.update);
router.delete('/orgs/:orgId', orgsCtrl.remove);

// ── roles ───────────────────────────────────────────────────────
router.get('/orgs/:orgId/roles', rolesCtrl.getOne);
router.post('/orgs/:orgId/roles', rolesCtrl.create);
router.get('/orgs/:orgId/roles/:roleId', rolesCtrl.getOne);
router.patch('/orgs/:orgId/roles/:roleId', rolesCtrl.update);
router.delete('/orgs/:orgId/roles/:roleId', rolesCtrl.remove);

// ── runbooks ────────────────────────────────────────────────────
router.get('/orgs/:orgId/runbooks/templates', runbooksCtrl.getOne);
router.post('/orgs/:orgId/runbooks/templates/compile', runbooksCtrl.create);
router.get('/orgs/:orgId/runbooks/templates/compilations/:compilationId', runbooksCtrl.getOne);
router.get('/orgs/:orgId/runbooks/templates/compilations/:compilationId/events', runbooksCtrl.getOne);
router.get('/orgs/:orgId/runbooks/templates/:runbookId', runbooksCtrl.getOne);
router.patch('/orgs/:orgId/runbooks/templates/:runbookId', runbooksCtrl.update);
router.get('/orgs/:orgId/runbooks/templates/:runbookId/versions', runbooksCtrl.getOne);
router.get('/orgs/:orgId/runbooks/templates/versions/:runbookVersionId', runbooksCtrl.getOne);
router.patch('/orgs/:orgId/runbooks/templates/versions/:runbookVersionId', runbooksCtrl.update);
router.get('/orgs/:orgId/runbooks/templates/versions/:runbookVersionId/diagnostics', runbooksCtrl.getOne);
router.post('/orgs/:orgId/runbooks/invocations/plan', runbooksCtrl.create);

// ── secrets ─────────────────────────────────────────────────────
router.get('/orgs/:orgId/secrets', secretsCtrl.getOne);
router.post('/orgs/:orgId/secrets', secretsCtrl.create);
router.get('/orgs/:orgId/secrets/:secretId', secretsCtrl.getOne);
router.patch('/orgs/:orgId/secrets/:secretId', secretsCtrl.update);
router.delete('/orgs/:orgId/secrets/:secretId', secretsCtrl.remove);
router.post('/orgs/:orgId/secrets/:secretId/value', secretsCtrl.create);

// ── signals ─────────────────────────────────────────────────────
router.get('/orgs/:orgId/signals/incidents', signalsCtrl.getOne);
router.get('/orgs/:orgId/signals/incidents/:incidentId', signalsCtrl.getOne);
router.get('/orgs/:orgId/signals/incidents/:incidentId/timeline', signalsCtrl.getOne);
router.get('/orgs/:orgId/signals/incidents/:incidentId/events', signalsCtrl.getOne);
router.get('/orgs/:orgId/signals', signalsCtrl.getOne);
router.get('/orgs/:orgId/signals/features', signalsCtrl.getOne);
router.get('/orgs/:orgId/signals/conditions', signalsCtrl.getOne);
router.get('/orgs/:orgId/signals/watchlist', signalsCtrl.getOne);

// ── sites ───────────────────────────────────────────────────────
router.get('/orgs/:orgId/sites', sitesCtrl.getOne);
router.post('/orgs/:orgId/sites', sitesCtrl.create);
router.get('/orgs/:orgId/sites/:siteId', sitesCtrl.getOne);
router.patch('/orgs/:orgId/sites/:siteId', sitesCtrl.update);
router.delete('/orgs/:orgId/sites/:siteId', sitesCtrl.remove);
router.get('/orgs/:orgId/sites/:siteId/connector-clusters', sitesCtrl.getOne);
router.get('/orgs/:orgId/sites/:siteId/topology', sitesCtrl.getOne);

// ── topology ────────────────────────────────────────────────────
router.get('/orgs/:orgId/topology', topologyCtrl.getOne);
router.get('/orgs/:orgId/topology/views', topologyCtrl.getOne);
router.post('/orgs/:orgId/topology/views', topologyCtrl.create);
router.get('/orgs/:orgId/topology/views/:viewId', topologyCtrl.getOne);
router.patch('/orgs/:orgId/topology/views/:viewId', topologyCtrl.update);
router.delete('/orgs/:orgId/topology/views/:viewId', topologyCtrl.remove);
router.get('/orgs/:orgId/topology/views/:viewId/params', topologyCtrl.getOne);
router.get('/orgs/:orgId/topology/views/:viewId/params/:paramName/options', topologyCtrl.getOne);
router.post('/orgs/:orgId/topology/views/:viewId/resolve', topologyCtrl.create);
router.post('/orgs/:orgId/topology/semantic-context:resolve', actionHandler('resolve'));
router.post('/orgs/:orgId/topology/overlays:compile', actionHandler('compile'));
router.get('/orgs/:orgId/topology/views/:viewId/stream', streamHandler);
router.get('/orgs/:orgId/topology/views/:viewId/definition', topologyCtrl.getOne);

// ── visibility ──────────────────────────────────────────────────
router.post('/orgs/:orgId/visibility/sessions', visibilityCtrl.create);
router.get('/orgs/:orgId/visibility/sessions/:sessionId', visibilityCtrl.getOne);
router.delete('/orgs/:orgId/visibility/sessions/:sessionId', visibilityCtrl.remove);
router.get('/orgs/:orgId/visibility/sessions/:sessionId/stream', streamHandler);
router.post('/orgs/:orgId/visibility/sessions/:sessionId/proposals', visibilityCtrl.create);
router.get('/orgs/:orgId/visibility/sessions/:sessionId/proposals/:proposalId', visibilityCtrl.getOne);
router.post('/orgs/:orgId/visibility/sessions/:sessionId/proposals/:proposalId:preview', actionHandler('preview'));
router.post('/orgs/:orgId/visibility/sessions/:sessionId/proposals/:proposalId:apply', actionHandler('apply'));
router.post('/orgs/:orgId/visibility/sessions/:sessionId/proposals/:proposalId:reject', actionHandler('reject'));
router.post('/orgs/:orgId/visibility/sessions/:sessionId:undo', actionHandler('undo'));

module.exports = router;